name: lastcowboyssbbot

on:
  schedule:
      - cron: '20 20 * * *'

jobs:
  cowboyssb-post:
    runs-on: macOS-latest
    env:
      COWBOYSSB_API_KEY: ${{ secrets.COWBOYSSB_API_KEY }}
      COWBOYSSB_API_SECRET: ${{ secrets.COWBOYSSB_API_SECRET }}
      COWBOYSSB_ACCESS_TOKEN: ${{ secrets.COWBOYSSB_ACCESS_TOKEN }}
      COWBOYSSB_ACCESS_TOKEN_SECRET: ${{ secrets.COWBOYSSB_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript cowboyssb_tweet.R
